export const methods = [
  'get',
  'post',
  'put',
  'patch',
  'delete',
  'head',
  'options'
];

export const statusCodes = [
  {
    id: 0,
    label: 'You can directly type non-listed codes (599, etc.)',
    disabled: true
  },
  {
    id: 1,
    label: 'Information responses (1xx)',
    codes: [
      { value: 100, label: 'Continue', hidden: false },
      { value: 101, label: 'Switching Protocols', hidden: false },
      { value: 102, label: 'Processing', hidden: false },
      { value: 103, label: 'Early Hints', hidden: false },
      { value: 104, label: 'Unknown', hidden: true },
      { value: 105, label: 'Unknown', hidden: true },
      { value: 106, label: 'Unknown', hidden: true },
      { value: 107, label: 'Unknown', hidden: true },
      { value: 108, label: 'Unknown', hidden: true },
      { value: 109, label: 'Unknown', hidden: true },
      { value: 110, label: 'Unknown', hidden: true },
      { value: 111, label: 'Unknown', hidden: true },
      { value: 112, label: 'Unknown', hidden: true },
      { value: 113, label: 'Unknown', hidden: true },
      { value: 114, label: 'Unknown', hidden: true },
      { value: 115, label: 'Unknown', hidden: true },
      { value: 116, label: 'Unknown', hidden: true },
      { value: 117, label: 'Unknown', hidden: true },
      { value: 118, label: 'Unknown', hidden: true },
      { value: 119, label: 'Unknown', hidden: true },
      { value: 120, label: 'Unknown', hidden: true },
      { value: 121, label: 'Unknown', hidden: true },
      { value: 122, label: 'Unknown', hidden: true },
      { value: 123, label: 'Unknown', hidden: true },
      { value: 124, label: 'Unknown', hidden: true },
      { value: 125, label: 'Unknown', hidden: true },
      { value: 126, label: 'Unknown', hidden: true },
      { value: 127, label: 'Unknown', hidden: true },
      { value: 128, label: 'Unknown', hidden: true },
      { value: 129, label: 'Unknown', hidden: true },
      { value: 130, label: 'Unknown', hidden: true },
      { value: 131, label: 'Unknown', hidden: true },
      { value: 132, label: 'Unknown', hidden: true },
      { value: 133, label: 'Unknown', hidden: true },
      { value: 134, label: 'Unknown', hidden: true },
      { value: 135, label: 'Unknown', hidden: true },
      { value: 136, label: 'Unknown', hidden: true },
      { value: 137, label: 'Unknown', hidden: true },
      { value: 138, label: 'Unknown', hidden: true },
      { value: 139, label: 'Unknown', hidden: true },
      { value: 140, label: 'Unknown', hidden: true },
      { value: 141, label: 'Unknown', hidden: true },
      { value: 142, label: 'Unknown', hidden: true },
      { value: 143, label: 'Unknown', hidden: true },
      { value: 144, label: 'Unknown', hidden: true },
      { value: 145, label: 'Unknown', hidden: true },
      { value: 146, label: 'Unknown', hidden: true },
      { value: 147, label: 'Unknown', hidden: true },
      { value: 148, label: 'Unknown', hidden: true },
      { value: 149, label: 'Unknown', hidden: true },
      { value: 150, label: 'Unknown', hidden: true },
      { value: 151, label: 'Unknown', hidden: true },
      { value: 152, label: 'Unknown', hidden: true },
      { value: 153, label: 'Unknown', hidden: true },
      { value: 154, label: 'Unknown', hidden: true },
      { value: 155, label: 'Unknown', hidden: true },
      { value: 156, label: 'Unknown', hidden: true },
      { value: 157, label: 'Unknown', hidden: true },
      { value: 158, label: 'Unknown', hidden: true },
      { value: 159, label: 'Unknown', hidden: true },
      { value: 160, label: 'Unknown', hidden: true },
      { value: 161, label: 'Unknown', hidden: true },
      { value: 162, label: 'Unknown', hidden: true },
      { value: 163, label: 'Unknown', hidden: true },
      { value: 164, label: 'Unknown', hidden: true },
      { value: 165, label: 'Unknown', hidden: true },
      { value: 166, label: 'Unknown', hidden: true },
      { value: 167, label: 'Unknown', hidden: true },
      { value: 168, label: 'Unknown', hidden: true },
      { value: 169, label: 'Unknown', hidden: true },
      { value: 170, label: 'Unknown', hidden: true },
      { value: 171, label: 'Unknown', hidden: true },
      { value: 172, label: 'Unknown', hidden: true },
      { value: 173, label: 'Unknown', hidden: true },
      { value: 174, label: 'Unknown', hidden: true },
      { value: 175, label: 'Unknown', hidden: true },
      { value: 176, label: 'Unknown', hidden: true },
      { value: 177, label: 'Unknown', hidden: true },
      { value: 178, label: 'Unknown', hidden: true },
      { value: 179, label: 'Unknown', hidden: true },
      { value: 180, label: 'Unknown', hidden: true },
      { value: 181, label: 'Unknown', hidden: true },
      { value: 182, label: 'Unknown', hidden: true },
      { value: 183, label: 'Unknown', hidden: true },
      { value: 184, label: 'Unknown', hidden: true },
      { value: 185, label: 'Unknown', hidden: true },
      { value: 186, label: 'Unknown', hidden: true },
      { value: 187, label: 'Unknown', hidden: true },
      { value: 188, label: 'Unknown', hidden: true },
      { value: 189, label: 'Unknown', hidden: true },
      { value: 190, label: 'Unknown', hidden: true },
      { value: 191, label: 'Unknown', hidden: true },
      { value: 192, label: 'Unknown', hidden: true },
      { value: 193, label: 'Unknown', hidden: true },
      { value: 194, label: 'Unknown', hidden: true },
      { value: 195, label: 'Unknown', hidden: true },
      { value: 196, label: 'Unknown', hidden: true },
      { value: 197, label: 'Unknown', hidden: true },
      { value: 198, label: 'Unknown', hidden: true },
      { value: 199, label: 'Unknown', hidden: true }
    ]
  },
  {
    id: 2,
    label: 'Successful responses (2xx)',
    codes: [
      { value: 200, label: 'OK', hidden: false },
      { value: 201, label: 'Created', hidden: false },
      { value: 202, label: 'Accepted', hidden: false },
      { value: 203, label: 'Non-Authoritative Information', hidden: false },
      { value: 204, label: 'No Content', hidden: false },
      { value: 205, label: 'Reset Content', hidden: false },
      { value: 206, label: 'Partial Content', hidden: false },
      { value: 207, label: 'Multi-Status', hidden: false },
      { value: 208, label: 'Already Reported', hidden: false },
      { value: 209, label: 'Unknown', hidden: true },
      { value: 210, label: 'Unknown', hidden: true },
      { value: 211, label: 'Unknown', hidden: true },
      { value: 212, label: 'Unknown', hidden: true },
      { value: 213, label: 'Unknown', hidden: true },
      { value: 214, label: 'Unknown', hidden: true },
      { value: 215, label: 'Unknown', hidden: true },
      { value: 216, label: 'Unknown', hidden: true },
      { value: 217, label: 'Unknown', hidden: true },
      { value: 218, label: 'This is fine (Apache Web Server)', hidden: false },
      { value: 219, label: 'Unknown', hidden: true },
      { value: 220, label: 'Unknown', hidden: true },
      { value: 221, label: 'Unknown', hidden: true },
      { value: 222, label: 'Unknown', hidden: true },
      { value: 223, label: 'Unknown', hidden: true },
      { value: 224, label: 'Unknown', hidden: true },
      { value: 225, label: 'Unknown', hidden: true },
      { value: 226, label: 'IM Used', hidden: false },
      { value: 227, label: 'Unknown', hidden: true },
      { value: 228, label: 'Unknown', hidden: true },
      { value: 229, label: 'Unknown', hidden: true },
      { value: 230, label: 'Unknown', hidden: true },
      { value: 231, label: 'Unknown', hidden: true },
      { value: 232, label: 'Unknown', hidden: true },
      { value: 233, label: 'Unknown', hidden: true },
      { value: 234, label: 'Unknown', hidden: true },
      { value: 235, label: 'Unknown', hidden: true },
      { value: 236, label: 'Unknown', hidden: true },
      { value: 237, label: 'Unknown', hidden: true },
      { value: 238, label: 'Unknown', hidden: true },
      { value: 239, label: 'Unknown', hidden: true },
      { value: 240, label: 'Unknown', hidden: true },
      { value: 241, label: 'Unknown', hidden: true },
      { value: 242, label: 'Unknown', hidden: true },
      { value: 243, label: 'Unknown', hidden: true },
      { value: 244, label: 'Unknown', hidden: true },
      { value: 245, label: 'Unknown', hidden: true },
      { value: 246, label: 'Unknown', hidden: true },
      { value: 247, label: 'Unknown', hidden: true },
      { value: 248, label: 'Unknown', hidden: true },
      { value: 249, label: 'Unknown', hidden: true },
      { value: 250, label: 'Unknown', hidden: true },
      { value: 251, label: 'Unknown', hidden: true },
      { value: 252, label: 'Unknown', hidden: true },
      { value: 253, label: 'Unknown', hidden: true },
      { value: 254, label: 'Unknown', hidden: true },
      { value: 255, label: 'Unknown', hidden: true },
      { value: 256, label: 'Unknown', hidden: true },
      { value: 257, label: 'Unknown', hidden: true },
      { value: 258, label: 'Unknown', hidden: true },
      { value: 259, label: 'Unknown', hidden: true },
      { value: 260, label: 'Unknown', hidden: true },
      { value: 261, label: 'Unknown', hidden: true },
      { value: 262, label: 'Unknown', hidden: true },
      { value: 263, label: 'Unknown', hidden: true },
      { value: 264, label: 'Unknown', hidden: true },
      { value: 265, label: 'Unknown', hidden: true },
      { value: 266, label: 'Unknown', hidden: true },
      { value: 267, label: 'Unknown', hidden: true },
      { value: 268, label: 'Unknown', hidden: true },
      { value: 269, label: 'Unknown', hidden: true },
      { value: 270, label: 'Unknown', hidden: true },
      { value: 271, label: 'Unknown', hidden: true },
      { value: 272, label: 'Unknown', hidden: true },
      { value: 273, label: 'Unknown', hidden: true },
      { value: 274, label: 'Unknown', hidden: true },
      { value: 275, label: 'Unknown', hidden: true },
      { value: 276, label: 'Unknown', hidden: true },
      { value: 277, label: 'Unknown', hidden: true },
      { value: 278, label: 'Unknown', hidden: true },
      { value: 279, label: 'Unknown', hidden: true },
      { value: 280, label: 'Unknown', hidden: true },
      { value: 281, label: 'Unknown', hidden: true },
      { value: 282, label: 'Unknown', hidden: true },
      { value: 283, label: 'Unknown', hidden: true },
      { value: 284, label: 'Unknown', hidden: true },
      { value: 285, label: 'Unknown', hidden: true },
      { value: 286, label: 'Unknown', hidden: true },
      { value: 287, label: 'Unknown', hidden: true },
      { value: 288, label: 'Unknown', hidden: true },
      { value: 289, label: 'Unknown', hidden: true },
      { value: 290, label: 'Unknown', hidden: true },
      { value: 291, label: 'Unknown', hidden: true },
      { value: 292, label: 'Unknown', hidden: true },
      { value: 293, label: 'Unknown', hidden: true },
      { value: 294, label: 'Unknown', hidden: true },
      { value: 295, label: 'Unknown', hidden: true },
      { value: 296, label: 'Unknown', hidden: true },
      { value: 297, label: 'Unknown', hidden: true },
      { value: 298, label: 'Unknown', hidden: true },
      { value: 299, label: 'Unknown', hidden: true }
    ]
  },
  {
    id: 3,
    label: 'Redirection messages (3xx)',
    codes: [
      { value: 300, label: 'Multiple Choices', hidden: false },
      { value: 301, label: 'Moved Permanently', hidden: false },
      { value: 302, label: 'Found', hidden: false },
      { value: 303, label: 'See Other', hidden: false },
      { value: 304, label: 'Not Modified', hidden: false },
      { value: 305, label: 'Use Proxy', hidden: false },
      { value: 306, label: '(Unused)', hidden: false },
      { value: 307, label: 'Temporary Redirect', hidden: false },
      { value: 308, label: 'Permanent Redirect', hidden: false },
      { value: 309, label: 'Unknown', hidden: true },
      { value: 310, label: 'Unknown', hidden: true },
      { value: 311, label: 'Unknown', hidden: true },
      { value: 312, label: 'Unknown', hidden: true },
      { value: 313, label: 'Unknown', hidden: true },
      { value: 314, label: 'Unknown', hidden: true },
      { value: 315, label: 'Unknown', hidden: true },
      { value: 316, label: 'Unknown', hidden: true },
      { value: 317, label: 'Unknown', hidden: true },
      { value: 318, label: 'Unknown', hidden: true },
      { value: 319, label: 'Unknown', hidden: true },
      { value: 320, label: 'Unknown', hidden: true },
      { value: 321, label: 'Unknown', hidden: true },
      { value: 322, label: 'Unknown', hidden: true },
      { value: 323, label: 'Unknown', hidden: true },
      { value: 324, label: 'Unknown', hidden: true },
      { value: 325, label: 'Unknown', hidden: true },
      { value: 326, label: 'Unknown', hidden: true },
      { value: 327, label: 'Unknown', hidden: true },
      { value: 328, label: 'Unknown', hidden: true },
      { value: 329, label: 'Unknown', hidden: true },
      { value: 330, label: 'Unknown', hidden: true },
      { value: 331, label: 'Unknown', hidden: true },
      { value: 332, label: 'Unknown', hidden: true },
      { value: 333, label: 'Unknown', hidden: true },
      { value: 334, label: 'Unknown', hidden: true },
      { value: 335, label: 'Unknown', hidden: true },
      { value: 336, label: 'Unknown', hidden: true },
      { value: 337, label: 'Unknown', hidden: true },
      { value: 338, label: 'Unknown', hidden: true },
      { value: 339, label: 'Unknown', hidden: true },
      { value: 340, label: 'Unknown', hidden: true },
      { value: 341, label: 'Unknown', hidden: true },
      { value: 342, label: 'Unknown', hidden: true },
      { value: 343, label: 'Unknown', hidden: true },
      { value: 344, label: 'Unknown', hidden: true },
      { value: 345, label: 'Unknown', hidden: true },
      { value: 346, label: 'Unknown', hidden: true },
      { value: 347, label: 'Unknown', hidden: true },
      { value: 348, label: 'Unknown', hidden: true },
      { value: 349, label: 'Unknown', hidden: true },
      { value: 350, label: 'Unknown', hidden: true },
      { value: 351, label: 'Unknown', hidden: true },
      { value: 352, label: 'Unknown', hidden: true },
      { value: 353, label: 'Unknown', hidden: true },
      { value: 354, label: 'Unknown', hidden: true },
      { value: 355, label: 'Unknown', hidden: true },
      { value: 356, label: 'Unknown', hidden: true },
      { value: 357, label: 'Unknown', hidden: true },
      { value: 358, label: 'Unknown', hidden: true },
      { value: 359, label: 'Unknown', hidden: true },
      { value: 360, label: 'Unknown', hidden: true },
      { value: 361, label: 'Unknown', hidden: true },
      { value: 362, label: 'Unknown', hidden: true },
      { value: 363, label: 'Unknown', hidden: true },
      { value: 364, label: 'Unknown', hidden: true },
      { value: 365, label: 'Unknown', hidden: true },
      { value: 366, label: 'Unknown', hidden: true },
      { value: 367, label: 'Unknown', hidden: true },
      { value: 368, label: 'Unknown', hidden: true },
      { value: 369, label: 'Unknown', hidden: true },
      { value: 370, label: 'Unknown', hidden: true },
      { value: 371, label: 'Unknown', hidden: true },
      { value: 372, label: 'Unknown', hidden: true },
      { value: 373, label: 'Unknown', hidden: true },
      { value: 374, label: 'Unknown', hidden: true },
      { value: 375, label: 'Unknown', hidden: true },
      { value: 376, label: 'Unknown', hidden: true },
      { value: 377, label: 'Unknown', hidden: true },
      { value: 378, label: 'Unknown', hidden: true },
      { value: 379, label: 'Unknown', hidden: true },
      { value: 380, label: 'Unknown', hidden: true },
      { value: 381, label: 'Unknown', hidden: true },
      { value: 382, label: 'Unknown', hidden: true },
      { value: 383, label: 'Unknown', hidden: true },
      { value: 384, label: 'Unknown', hidden: true },
      { value: 385, label: 'Unknown', hidden: true },
      { value: 386, label: 'Unknown', hidden: true },
      { value: 387, label: 'Unknown', hidden: true },
      { value: 388, label: 'Unknown', hidden: true },
      { value: 389, label: 'Unknown', hidden: true },
      { value: 390, label: 'Unknown', hidden: true },
      { value: 391, label: 'Unknown', hidden: true },
      { value: 392, label: 'Unknown', hidden: true },
      { value: 393, label: 'Unknown', hidden: true },
      { value: 394, label: 'Unknown', hidden: true },
      { value: 395, label: 'Unknown', hidden: true },
      { value: 396, label: 'Unknown', hidden: true },
      { value: 397, label: 'Unknown', hidden: true },
      { value: 398, label: 'Unknown', hidden: true },
      { value: 399, label: 'Unknown', hidden: true }
    ]
  },
  {
    id: 4,
    label: 'Client error responses (4xx)',
    codes: [
      { value: 400, label: 'Bad Request', hidden: false },
      { value: 401, label: 'Unauthorized', hidden: false },
      { value: 402, label: 'Payment Required', hidden: false },
      { value: 403, label: 'Forbidden', hidden: false },
      { value: 404, label: 'Not Found', hidden: false },
      { value: 405, label: 'Method Not Allowed', hidden: false },
      { value: 406, label: 'Not Acceptable', hidden: false },
      { value: 407, label: 'Proxy Authentication Required', hidden: false },
      { value: 408, label: 'Request Timeout', hidden: false },
      { value: 409, label: 'Conflict', hidden: false },
      { value: 410, label: 'Gone', hidden: false },
      { value: 411, label: 'Length Required', hidden: false },
      { value: 412, label: 'Precondition Failed', hidden: false },
      { value: 413, label: 'Payload Too Large', hidden: false },
      { value: 414, label: 'URI Too Long', hidden: false },
      { value: 415, label: 'Unsupported Media Type', hidden: false },
      { value: 416, label: 'Range Not Satisfiable', hidden: false },
      { value: 417, label: 'Expectation Failed', hidden: false },
      { value: 418, label: "I'm a teapot", hidden: false },
      { value: 419, label: 'Page Expired (Laravel Framework)', hidden: false },
      { value: 420, label: 'Method Failure (Spring Framework)', hidden: false },
      { value: 421, label: 'Misdirected Request', hidden: false },
      { value: 422, label: 'Unprocessable Entity', hidden: false },
      { value: 423, label: 'Locked', hidden: false },
      { value: 424, label: 'Failed Dependency', hidden: false },
      { value: 425, label: 'Too Early', hidden: false },
      { value: 426, label: 'Upgrade Required', hidden: false },
      { value: 427, label: 'Unknown', hidden: true },
      { value: 428, label: 'Precondition Required', hidden: false },
      { value: 429, label: 'Too Many Requests', hidden: false },
      {
        value: 430,
        label: 'Request Header Fields Too Large (Shopify)',
        hidden: false
      },
      { value: 431, label: 'Request Header Fields Too Large', hidden: false },
      { value: 432, label: 'Unknown', hidden: true },
      { value: 433, label: 'Unknown', hidden: true },
      { value: 434, label: 'Unknown', hidden: true },
      { value: 435, label: 'Unknown', hidden: true },
      { value: 436, label: 'Unknown', hidden: true },
      { value: 437, label: 'Unknown', hidden: true },
      { value: 438, label: 'Unknown', hidden: true },
      { value: 439, label: 'Unknown', hidden: true },
      { value: 440, label: 'Login Time-out (IIS)', hidden: false },
      { value: 441, label: 'Unknown', hidden: true },
      { value: 442, label: 'Unknown', hidden: true },
      { value: 443, label: 'Unknown', hidden: true },
      { value: 444, label: 'No Response (nginx)', hidden: false },
      { value: 445, label: 'Unknown', hidden: true },
      { value: 446, label: 'Unknown', hidden: true },
      { value: 447, label: 'Unknown', hidden: true },
      { value: 448, label: 'Unknown', hidden: true },
      { value: 449, label: 'Retry With (IIS)', hidden: false },
      {
        value: 450,
        label: 'Blocked by Windows Parental Controls (Microsoft)',
        hidden: false
      },
      { value: 451, label: 'Unavailable For Legal Reasons', hidden: false },
      { value: 452, label: 'Unknown', hidden: true },
      { value: 453, label: 'Unknown', hidden: true },
      { value: 454, label: 'Unknown', hidden: true },
      { value: 455, label: 'Unknown', hidden: true },
      { value: 456, label: 'Unknown', hidden: true },
      { value: 457, label: 'Unknown', hidden: true },
      { value: 458, label: 'Unknown', hidden: true },
      { value: 459, label: 'Unknown', hidden: true },
      {
        value: 460,
        label: 'Client closed connection (AWS ELB)',
        hidden: false
      },
      { value: 461, label: 'Unknown', hidden: true },
      { value: 462, label: 'Unknown', hidden: true },
      { value: 463, label: 'Unknown', hidden: true },
      { value: 464, label: 'Unknown', hidden: true },
      { value: 465, label: 'Unknown', hidden: true },
      { value: 466, label: 'Unknown', hidden: true },
      { value: 467, label: 'Unknown', hidden: true },
      { value: 468, label: 'Unknown', hidden: true },
      { value: 469, label: 'Unknown', hidden: true },
      { value: 470, label: 'Unknown', hidden: true },
      { value: 471, label: 'Unknown', hidden: true },
      { value: 472, label: 'Unknown', hidden: true },
      { value: 473, label: 'Unknown', hidden: true },
      { value: 474, label: 'Unknown', hidden: true },
      { value: 475, label: 'Unknown', hidden: true },
      { value: 476, label: 'Unknown', hidden: true },
      { value: 477, label: 'Unknown', hidden: true },
      { value: 478, label: 'Unknown', hidden: true },
      { value: 479, label: 'Unknown', hidden: true },
      { value: 480, label: 'Unknown', hidden: true },
      { value: 481, label: 'Unknown', hidden: true },
      { value: 482, label: 'Unknown', hidden: true },
      { value: 483, label: 'Unknown', hidden: true },
      { value: 484, label: 'Unknown', hidden: true },
      { value: 485, label: 'Unknown', hidden: true },
      { value: 486, label: 'Unknown', hidden: true },
      { value: 487, label: 'Unknown', hidden: true },
      { value: 488, label: 'Unknown', hidden: true },
      { value: 489, label: 'Unknown', hidden: true },
      { value: 490, label: 'Unknown', hidden: true },
      { value: 491, label: 'Unknown', hidden: true },
      { value: 492, label: 'Unknown', hidden: true },
      { value: 493, label: 'Unknown', hidden: true },
      { value: 494, label: 'Request header too large (nginx)', hidden: false },
      { value: 495, label: 'SSL Certificate Error (nginx)', hidden: false },
      { value: 496, label: 'SSL Certificate Required (nginx)', hidden: false },
      {
        value: 497,
        label: 'HTTP Request Sent to HTTPS Port (nginx)',
        hidden: false
      },
      { value: 498, label: 'Unknown', hidden: true },
      { value: 499, label: 'Client Closed Request (nginx)', hidden: false }
    ]
  },
  {
    id: 5,
    label: 'Server error responses (5xx)',
    codes: [
      { value: 500, label: 'Internal Server Error', hidden: false },
      { value: 501, label: 'Not Implemented', hidden: false },
      { value: 502, label: 'Bad Gateway', hidden: false },
      { value: 503, label: 'Service Unavailable', hidden: false },
      { value: 504, label: 'Gateway Timeout', hidden: false },
      { value: 505, label: 'HTTP Version Not Supported', hidden: false },
      { value: 506, label: 'Variant Also Negotiates', hidden: false },
      { value: 507, label: 'Insufficient Storage', hidden: false },
      { value: 508, label: 'Loop Detected', hidden: false },
      {
        value: 509,
        label: 'Bandwidth Limit Exceeded (Apache Web Server)',
        hidden: false
      },
      { value: 510, label: 'Not Extended', hidden: false },
      { value: 511, label: 'Network Authentication Required', hidden: false },
      { value: 512, label: 'Unknown', hidden: true },
      { value: 513, label: 'Unknown', hidden: true },
      { value: 514, label: 'Unknown', hidden: true },
      { value: 515, label: 'Unknown', hidden: true },
      { value: 516, label: 'Unknown', hidden: true },
      { value: 517, label: 'Unknown', hidden: true },
      { value: 518, label: 'Unknown', hidden: true },
      { value: 519, label: 'Unknown', hidden: true },
      {
        value: 520,
        label: 'Web Server Returned an Unknown Error (Cloudflare)',
        hidden: false
      },
      { value: 521, label: 'Web Server Is Down (Cloudflare)', hidden: false },
      { value: 522, label: 'Connection Timed Out (Cloudflare)', hidden: false },
      {
        value: 523,
        label: 'Origin Is Unreachable (Cloudflare)',
        hidden: false
      },
      { value: 524, label: 'A Timeout Occurred (Cloudflare)', hidden: false },
      { value: 525, label: 'SSL Handshake Failed (Cloudflare)', hidden: false },
      {
        value: 526,
        label: 'Invalid SSL Certificate (Cloudflare)',
        hidden: false
      },
      { value: 527, label: 'Railgun Error (Cloudflare)', hidden: false },
      { value: 528, label: 'Unknown', hidden: true },
      { value: 529, label: 'Unknown', hidden: true },
      { value: 530, label: 'Unknown', hidden: true },
      { value: 531, label: 'Unknown', hidden: true },
      { value: 532, label: 'Unknown', hidden: true },
      { value: 533, label: 'Unknown', hidden: true },
      { value: 534, label: 'Unknown', hidden: true },
      { value: 535, label: 'Unknown', hidden: true },
      { value: 536, label: 'Unknown', hidden: true },
      { value: 537, label: 'Unknown', hidden: true },
      { value: 538, label: 'Unknown', hidden: true },
      { value: 539, label: 'Unknown', hidden: true },
      { value: 540, label: 'Unknown', hidden: true },
      { value: 541, label: 'Unknown', hidden: true },
      { value: 542, label: 'Unknown', hidden: true },
      { value: 543, label: 'Unknown', hidden: true },
      { value: 544, label: 'Unknown', hidden: true },
      { value: 545, label: 'Unknown', hidden: true },
      { value: 546, label: 'Unknown', hidden: true },
      { value: 547, label: 'Unknown', hidden: true },
      { value: 548, label: 'Unknown', hidden: true },
      { value: 549, label: 'Unknown', hidden: true },
      { value: 550, label: 'Unknown', hidden: true },
      { value: 551, label: 'Unknown', hidden: true },
      { value: 552, label: 'Unknown', hidden: true },
      { value: 553, label: 'Unknown', hidden: true },
      { value: 554, label: 'Unknown', hidden: true },
      { value: 555, label: 'Unknown', hidden: true },
      { value: 556, label: 'Unknown', hidden: true },
      { value: 557, label: 'Unknown', hidden: true },
      { value: 558, label: 'Unknown', hidden: true },
      { value: 559, label: 'Unknown', hidden: true },
      { value: 560, label: 'Unknown', hidden: true },
      { value: 561, label: 'Unauthorized (AWS ELB)', hidden: false },
      { value: 562, label: 'Unknown', hidden: true },
      { value: 563, label: 'Unknown', hidden: true },
      { value: 564, label: 'Unknown', hidden: true },
      { value: 565, label: 'Unknown', hidden: true },
      { value: 566, label: 'Unknown', hidden: true },
      { value: 567, label: 'Unknown', hidden: true },
      { value: 568, label: 'Unknown', hidden: true },
      { value: 569, label: 'Unknown', hidden: true },
      { value: 570, label: 'Unknown', hidden: true },
      { value: 571, label: 'Unknown', hidden: true },
      { value: 572, label: 'Unknown', hidden: true },
      { value: 573, label: 'Unknown', hidden: true },
      { value: 574, label: 'Unknown', hidden: true },
      { value: 575, label: 'Unknown', hidden: true },
      { value: 576, label: 'Unknown', hidden: true },
      { value: 577, label: 'Unknown', hidden: true },
      { value: 578, label: 'Unknown', hidden: true },
      { value: 579, label: 'Unknown', hidden: true },
      { value: 580, label: 'Unknown', hidden: true },
      { value: 581, label: 'Unknown', hidden: true },
      { value: 582, label: 'Unknown', hidden: true },
      { value: 583, label: 'Unknown', hidden: true },
      { value: 584, label: 'Unknown', hidden: true },
      { value: 585, label: 'Unknown', hidden: true },
      { value: 586, label: 'Unknown', hidden: true },
      { value: 587, label: 'Unknown', hidden: true },
      { value: 588, label: 'Unknown', hidden: true },
      { value: 589, label: 'Unknown', hidden: true },
      { value: 590, label: 'Unknown', hidden: true },
      { value: 591, label: 'Unknown', hidden: true },
      { value: 592, label: 'Unknown', hidden: true },
      { value: 593, label: 'Unknown', hidden: true },
      { value: 594, label: 'Unknown', hidden: true },
      { value: 595, label: 'Unknown', hidden: true },
      { value: 596, label: 'Unknown', hidden: true },
      { value: 597, label: 'Unknown', hidden: true },
      { value: 598, label: 'Unknown', hidden: true },
      { value: 599, label: 'Unknown', hidden: true }
    ]
  }
];

export const headerNames = [
  'Accept',
  'Accept-CH',
  'Accept-Charset',
  'Accept-Features',
  'Accept-Encoding',
  'Accept-Language',
  'Accept-Ranges',
  'Access-Control-Allow-Credentials',
  'Access-Control-Allow-Origin',
  'Access-Control-Allow-Methods',
  'Access-Control-Allow-Headers',
  'Access-Control-Max-Age',
  'Access-Control-Expose-Headers',
  'Access-Control-Request-Method',
  'Access-Control-Request-Headers',
  'Age',
  'Allow',
  'Alternates',
  'Authorization',
  'Cache-Control',
  'Connection',
  'Content-Encoding',
  'Content-Language',
  'Content-Length',
  'Content-Location',
  'Content-MD5',
  'Content-Range',
  'Content-Security-Policy',
  'Content-Type',
  'Cookie',
  'DNT',
  'Date',
  'ETag',
  'Expect',
  'Expires',
  'From',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Last-Event-ID',
  'Last-Modified',
  'Link',
  'Location',
  'Max-Forwards',
  'Negotiate',
  'Origin',
  'Pragma',
  'Proxy-Authenticate',
  'Proxy-Authorization',
  'Range',
  'Referer',
  'Retry-After',
  'Sec-Websocket-Extensions',
  'Sec-Websocket-Key',
  'Sec-Websocket-Origin',
  'Sec-Websocket-Protocol',
  'Sec-Websocket-Version',
  'Server',
  'Set-Cookie',
  'Set-Cookie2',
  'Strict-Transport-Security',
  'TCN',
  'TE',
  'Trailer',
  'Transfer-Encoding',
  'Upgrade',
  'User-Agent',
  'Variant-Vary',
  'Vary',
  'Via',
  'Warning',
  'WWW-Authenticate',
  'X-Content-Duration',
  'X-Content-Security-Policy',
  'X-DNSPrefetch-Control',
  'X-Frame-Options',
  'X-Requested-With'
];

// values used to suggest
export const headerValues = [
  // content types
  'text/plain',
  'text/html',
  'application/json',
  'application/xml',
  'multipart/form-data',
  'application/xhtml+xml',
  'application/x-www-form-urlencoded',
  'text/csv',
  'text/css',
  'application/javascript',
  'application/zip',
  'application/pdf',
  'application/sql',
  'application/graphql',
  'application/ld+json',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.oasis.opendocument.text',
  'audio/mpeg',
  'audio/vorbis',
  'image/png',
  'image/jpeg',
  'image/gif',

  // authorization
  'Basic ',
  'Bearer ',
  'Digest ',
  'HOBA ',
  'Mutual ',
  'AWS4-HMAC-SHA256 ',

  // cache control
  'max-age=',
  'max-stale=',
  'min-fresh=',
  'no-cache',
  'no-store',
  'no-transform',
  'only-if-cached',
  'must-revalidate',
  'no-cache',
  'no-store',
  'no-transform',
  'public',
  'private',
  'proxy-revalidate',
  's-maxage=',

  // charset
  'US-ASCII',
  'ISO-8859-1',
  'UTF-8',
  'UTF-16BE',
  'UTF-16LE',
  'UTF-16'
];
